dutchiepay/src/app/(routes)/mypage/info/page.jsx, dutchiepay/src/app/(routes)/signup/page.jsx, dutchiepay/src/app/_components/_user/GetLocation.jsx
ex) feat/회원가입_API -> main
1. 로그인 API 호출
2. 회원가입 API 호출
3. 회원가입/마이페이지 회원정보 페이지 내의 getLocation 함수를 컴포넌트화하여 재사용
※ API 호출은 회의 시간에 함께 진행했던 내용이므로 결과를 생략합니다.
회원가입 페이지 접근 시 위치정보 불러오기
default 값 = 평택시 -> 재설정 버튼 클릭 시 춘천시로 변경
getLocation 함수 컴포넌트화
- Promise를 사용하여 값을 반환함으로써 위치정보를 불러온 뒤에 set 함수를 실행할 수 있도록 기존 함수 수정 (초기 undefined 값 나오지 않도록 설정)
- Promise 중 resolve를 반환하도록 구현 위치정보를 불러오지 못했을 때도 에러 문구를 표시하도록 resolve로 전달
- 위치 정보 에러 문구를 보다 명확히 하여 어떠한 오류로 불러오지 못했는지를 확실하게 표
=> [feat] 회원가입/로그인 API 호출 / [refactor] 위치정보 컴포넌트 분리

dutchiepay/src/app/(routes)/signup/page.jsx, dutchiepay/src/app/_components/_user/GetLocation.jsx, dutchiepay/src/app/_components/_user/PhoneAuth.jsx
ex) feat/signup-system-> dev
회원가입 유효성 검사 더 엄격하게 진행하였습니다. 
현재 인증 번호 시간이 지나면 인증 번호 입력 input이 자동으로 제거되게 구현했습니다 더 좋은 방법 있으면 말해주세요 ! 그리고 현재 인증하기 버튼 횟수 제한이 없어서 계속 API호출이 가능합니다 이 부분도 제한을 주는 게 어떨지 의견 남깁니다 !
=> [feat] 회원가입 유효성 강화, 휴대폰 인증 컴포넌트 분리, GeoLocation 불필요한 코드 제거

dutchiepay/next.config.mjs, dutchiepay/src/app/(routes)/mypage/page.jsx
ex) fix/redirect-static -> main
export 설정 시 커스텀 리디렉션 사용 불가능으로 인해 수동 리디렉션 설정으로 변경
1. 'next/navigation'의 redirect를 이용해 /mypage 접속 시 리디렉션을 진행하려고 했으나 아래와 같이 /mypage에 접속해 있는 동안 content 영역이 없어 footer가 위로 올라오고 sidebar에 가려지는 현상이 잠깐 표시되는 경우가 발생 -> 속도 저하(slow 4G)를 하지 않을 때도 footer의 일부분이 깜빡이는 것으로 보임 (recirect는 return 영역에 접근 불가능하여 height를 지정할 수 없음)
2. 'next/navigation'의 useRouter를 이용해 클라이언트 측에서 /mypage 접속 시 /mypage/info로 route 되도록 설정하고 content의 height를 지정하여 /mypage에서도 content 영역이 확보되는 방법으로 결정 
(※ URL 참고) /mypage 접근 시 content 확보 (첨부된 이미지는 마지막 commit 이전 기준으로 현재는 footer가 하단에 붙도록 수정, 디바이스마다 다르게 표시될 수 있음. calc 지원 불가능으로 추후 방법 고안 예정)
=> [fix] 수동 리디렉션 설정으로 변경

dutchiepay/src/app/(routes)/mypage/info/page.jsx
ex) feat/mypage-info-system -> main
회원 정보 수정  변경 취소 시 기존 유저 정보로 변경 완료 시 변경된 유저 정보로 바뀌게 구현
=> [feat] 회원 정보 수정  변경 취소 시 기존 유저 정보로 변경 완료 시 변경된 유저 정보로 바뀌게 구현

dutchiepay/package-lock.json, dutchiepay/package.json, dutchiepay/src/app/(routes)/login/page.jsx, dutchiepay/src/app/_components/_layout/Header.jsx, dutchiepay/src/app/_components/_layout/Sidebar.jsx, dutchiepay/src/app/layoutClient.js, dutchiepay/src/redux/slice/loginSlice.js, dutchiepay/src/redux/store.js
feat/login -> main
1. 로그인 API 호출
2. 로그인으로 받은 사용자 정보 redux 저장
3. 자동로그인 체크 여부에 따른 refresh 쿠키 저장 (세션/지속 쿠키) - 지속 쿠키의 경우 30일동안 저장되도록 임시 구현
4. 로그아웃 시 refresh 토큰 삭제 (로그아웃 api 호출  X)
5. redux-persist로 sessionstorage에 redux 변수 저장으로 데이터 유지
6. header/sidebar 사용자 정보 표시
로그인 시 header에 닉네임 및 프로필 이미지 표시 (현재 default profileImage는 임시 상태)
sidebar에서 닉네임과 프로필 이미지 redux 값으로 표시
serializability dev check middleware가 자동적으로 실행되어 serializableCheck를 false로 지정해 해
[serializableCheck 관련 에러 해결](https://github.com/rt2zz/redux-persist/issues/988)
+ 이전 회의에서 redux를 local에 저장하는 것으로 결정했으나 이 경우, 자동로그인으로 설정하지 않은 회원이 로그아웃하고 브라우저를 닫았을 때, redux 관련 데이터들은 유지되지만 refresh가 사라지는 상황이 발생하여 session에 저장하도록 수정하였습니다.
=> [feat] 로그인 API, 로그인 정보 redux 및 쿠키 저장

dutchiepay/package-lock.json, dutchiepay/package.json, dutchiepay/src/app/(routes)/mypage/info/page.jsx
ex) feat/image-upload
1. 이미지 업로드 button 클릭 시 input[type=file]이 실행되도록 함
2. 파일 업로드 시 jpg/jpeg, png 확장자를 가진 파일 여부를 체크해 그 외 파일 확장자는 return
3. 확장자 검사를 통과한 파일이 10MB를 넘어갈 경우에 return
4. 2/3번 유효성 검사가 통과된 후 uuid를 이용해 파일 이름이 중복되지 않도록 저장할 파일 이름 설정
5. 이미지 업로드 API 호출을 통해 S3에 업로드할 수 있는 presignedURL을 반환받음.
6. 해당 URL을 통해 S3 버킷에 이미지 업로드
7. 업로드된 이미지 URL imageURL에 저장 -> 현재 회원정보 수정 코드가 수정 중이므로 수정정보에 저장하지 않고 별도 변수에 저장. 확인을 위해 console에 URL 출력되도록 구현.
[업로드된 이미지, URL 참고](https://dutchiepay-image.s3.amazonaws.com/f12650bb-7e5b-46ea-bf14-804528bcef7f184784283_1991282151035642_8346224865736594101_n.jpg)
이미지  업로드 관련 코드를 추후 컴포넌트로 분리를 생각 중입니다. 현재 /info 페이지를 같이 작업 중이기 때문에 충돌을 고려해 컴포넌트를 분리하지 않고 push 했습니다.
=> [feat] 파일 불러오기 후 유효성 검사 통과된 이미지만 S3 업로드 구현

dutchiepay/src/app/(routes)/login/page.jsx, dutchiepay/src/app/_components/_user/LastLogin.jsx, dutchiepay/src/app/_components/_user/SignUpSubmit.jsx, dutchiepay/src/app/_components/_user/SocialLogin.jsx, dutchiepay/src/redux/slice/loginSlice.js
ex) feat/Last-login -> main
1. 기존 login 완료 시, redux(session)에 저장되던 loginType을 localStorage에 저장
2. /login 페이지 렌더링 시, localStorage로부터 loginType을 불러와 소셜로그인일 경우 해당하는 소셜 버튼 하단에 표시
3. 코드 중복을 줄이기 위해 최근 로그인 표시는 컴포넌트로 분리하여 type 값을 통해 표시
4. 소셜 로그인 컴포넌트 분리
5. 회원가입 성공 시, 해당 페이지에 그대로 남아있지 않고 메인으로 이동하도록 라우팅
6. 최근 로그인 표시 div의 aria-hidden 값이 loginType에 맞게 변경되도록 수정
※ 현재 소셜 로그인 구현이 안 되어 로그인 시 localStorage에 "kakao"가 무조건 저장되도록 코드를 수정한 뒤 테스트 (push된 코드는 실제값으로 저장됩니다)
세분화된 로그인 컴포넌트 분리를 고민했으나... 모든 내용이 로그인과 연관되어 있고, form 안에 일부 요소가 로그인 submit과 관련없으나 UI 상 form 안에 위치하여 별도 분리가 어려울 것으로 판단해 진행하지 않았습니다. (모든 요소를 분리한다면 가능은 하지만 현재 목적과는 맞지 않은 것 같아 진행하지 않았습니다.)
=> [feat, fix] 최근 로그인 방식 표시 및 컴포넌트 분리

dutchiepay/src/app/_components/_layout/Header.jsx
feat/relogin
1. header가 처음 렌더링 될 때 cookie에 refresh가 존재할 경우, relogin API 호출
현재 해당 API는 백엔드에서 merge가 되지 않아 테스트는 생략합니다.
refresh 만료 오류 문구 반환 시 로그아웃 처리 구현이 필요합니다. 현재 오류 메시지 관련 내용이 명세서에 없어 추후 추가되는대로 구현 예정입니다.
=> [feat] refresh token 존재 시, relogin API 호출

dutchiepay/src/app/(modals)/change-number/page.jsx, dutchiepay/src/app/(routes)/mypage/info/page.jsx, dutchiepay/src/app/_components/_layout/Sidebar.jsx, dutchiepay/src/app/_components/_user/GetLocation.jsx, dutchiepay/src/app/_components/_user/NicknameInput.jsx, dutchiepay/src/app/_components/_user/ResetSubmit.jsx, dutchiepay/src/app/hooks/useReissueToken.jsx, dutchiepay/src/redux/slice/loginSlice.js
ex) feat/password-change -> main
reissue,로그아웃,닉네임중복검사 API호출, 위치정보 error시 default지역으로 설정 및 alert 띄우기구현했습니다.
* UI변경 없는것은 컴포넌트 보단 커스텀훅이 더 좋다고해서 커스텀훅으로 작성했습니다.
분기 처리 해야 할 것
1. refresh토큰 만료
2. 비정상적인 접근
2가지 경우 로그아웃 진행해야할듯 합니다. 확정나면 기능 구현하겠습니다.
현재 onBlur이벤트로 처리했습니다.
=> [feat]reissue,로그아웃,닉네임중복검사 API호출, 위치정보 error시 default지역으로 설정 및 alert 띄우기

dutchiepay/src/app/_components/_user/GetLocation.jsx
ex) refator/geoLocation -> main
**중구, 동구, 서구, 남구, 북구만 area1 포함 area2까지
ex) 서울특별시 중구, 인천광역시 중구
나머지는 area2 (띄어쓰기 있을 시 앞 부분만)
ex) 마포구, 부천시**
=> [refactor] 위치정보 중복되지 않도록 표시 방법 변경

dutchiepay/src/app/_components/_user/SocialLogin.jsx, dutchiepay/src/app/_components/_user/SocialSignup.jsx
…그인 처리
fix/oauth-decryption
1. 기존 소셜로그인 과정 중 response를 복호화 하는 과정을 추가했습니다.
2. 복호화 하기 위한 데이터를 수신하는 과정에서 소셜로그인과 관계없는 message를 수신해 복호화를 하는 오류가 있어 소셜 로그인을 확인할 수 있도록 type을 전달받는 로직으로 수정되어 event.data.type이 "OAUTH_LOGIN"일 경우에만 해당 데이터를 복호화하도록 수정했습니다.
현재 해당 API가 배포되지 않아 테스트는 생략하였습니다.
message를 전달하는 과정에서 아직 제대로 전달되는지 체크되지 못했을 뿐더러 복호화가 제대로 이루어지는지는 체크하지 못했습니다. 클라이언트 내에 복호화는 제대로 동작하나 서버-클라이언트 복호화는 소셜로그인 뿐이라 해당 부분에서도 수정사항이 있을 수 있습니다. 테스트로 인해 테스트 없이 배포되었습니다. 추후 오류 발견 시 수정하겠습니다.
=> [fix] 소셜 로그인/회원가입 성공 시 데이터 복호화 및 로그인 처리

dutchiepay/src/app/_components/_user/EmailInput.jsx, dutchiepay/src/app/_components/_user/FindSubmit.jsx, dutchiepay/src/app/_components/_user/NicknameInput.jsx, dutchiepay/src/app/_components/_user/PasswordInput.jsx, dutchiepay/src/app/_components/_user/PhoneAuth.jsx, dutchiepay/src/app/_components/_user/ResetSubmit.jsx, dutchiepay/src/app/_components/_user/SignUpSubmit.jsx
ex) feat/user-system -> main
회원 비밀번호 재설정 시 현재 비밀번호 추가, 이메일,닉네임 중복검사, 전화번호 필수로 입력하게 구현했습니다.
1. 현재 회원가입 시 touchedFields 때문에 실시간으로 처리하는데 중복 API호출은 onBlur이라 input에서 포커스 해제시 호출해서 논리적으로 이상합니다... 다른 방법 찾아보겠습니다 !
2, 현재 비밀번호 input 유효성 검사를 어떻게 해야 할 지 모르겠습니다.. 저희 쪽에서 현재 password정보를 불러올 방법을 찾아야,, 실시간 유효성 검사가 가능할듯한데 잘 모르겠어요..
3. 이메일 컴포넌트를 비밀번호 재설정(find페이지)랑 회원가입 페이지에서 동시에 사용함으로 isFind 변수를 추가해줬습니다.
=> [feat] 회원 비밀번호 재설정 시 현재 비밀번호 추가, 이메일,닉네임 중복검사, 전화번호 필수로 입력하게 구현

dutchiepay/next.config.mjs, dutchiepay/src/app/(modals)/delivery-address/page.jsx, dutchiepay/src/app/_components/_layout/Header.jsx, dutchiepay/src/app/_components/_mypage/DeliveryAddress.jsx, dutchiepay/src/app/_components/_mypage/DeliveryAddressItem.jsx, dutchiepay/src/redux/slice/addressSlice.js, dutchiepay/src/redux/slice/loginSlice.js
fix/delivery-address
1. 배송지 관련 API 수정 사항 반영
2. 배송지 수정/삭제/추가 동작 시 address redux 값들 재암호화하여 저장
3. 배송지 호출 시 복호화 오류나지 않도록 수정
4. 로그아웃 시 redux 값 null로 수정 -> 이에 대한 오류는 하단 참고
5. 배송지 수정 시 팝업창으로 데이터 전달
6. 배송지 수정/추가 시 /info로 데이터 전달하여 처리 내용 deliveryAddress에 반영시켜 실시간으로 재렌더링
7. address redux 초기 값 ([])에서 (null)로 변경 -> 주소가 []일 때 init을 실행하도록 하였기 때문에 주소지를 설정하지 않은 사용자는 항상 재호출을 하고 있어 성능저하 발생. 초기값을 null로 변경하여 null과 []을 구분하여 재호출을 최소화
8. reducer setAddresses 제외 전부 삭제 -> redux는 데이터를 유지하기 위한 수단이고 암호화가 되어 있어 reducer로 address를 관리하려면 복호화 과정이 불필요하게 많아지기 때문에 초기 실행 시 useState에 addresses를 담아두고 해당 데이터를 set 함수를 이용해 처리하도록 변경 
처리 시 문제 없이 동작
★ 현재 delete 함수에 body로 addressId를 전달하도록 API가 설계되었으나 일반적으로 delete는 body를 포함하지 않도록 설계되어 있어 axios에서도 body에 담을 시 data로 전달되지 않고 별도의 데이터로 전달되어 API 오류가 발생합니다. 이에 대한 처리로 data에 addressId를 담아 전달해 …
=> [Fix] 배송지 호출 관련 오류 해결 및 추가/수정/삭제 API 처리

dutchiepay/src/app/(modals)/delivery-address/page.jsx, dutchiepay/src/app/_components/_commerce/Orderer.jsx, dutchiepay/src/app/_components/_layout/Header.jsx, dutchiepay/src/app/_components/_mypage/DeliveryAddress.jsx, dutchiepay/src/app/_components/_mypage/DeliveryAddressItem.jsx, dutchiepay/src/app/_components/_user/EmailInput.jsx, dutchiepay/src/app/_components/_user/SocialLogin.jsx
fix/delivery-address -> main 
1. 배송지 입력 시 지번주소가 아닌 도로명 주소로 받아오도록 수정 -> order 페이지의 우편번호 찾기 또한 수정
2. 배송지 추가/수정/삭제 시 해당 값을 클라이언트에서 직접 처리하지 않고 API를 재호출하도록 변경 -> 이중 처리 작업하지 않도록 변경
3. 배송지 수정 페이지 새로고침 시 데이터 소멸되는 오류 해결 -> 기존 데이터는 postMessageAPI를 이용해 수정 팝업 open 시 데이터를 전달하는 방식으로 구현했었습니다. 새로고침 이후 데이터를 유지할 수 없기 때문에 해당 방법 대신 redux에 저장되어 있는 값을 복호화하여 가져오도록 수정했습니다.
API 호출 시 문제 없이 API 호출 진행 됨. 삭제는 현재 API 미구현으로 체크해보지 못했으나 같은 방법으로 구현했으므로 문제 없을 것으로 예상
배송지 수정 시 데이터 새로고침 이후에도 유지 확인
이전 테스트에서 불러와지지 않던 아래 주소
도로명 주소로 문제없이 불러와짐 (도로명/지번 어떤 걸 선택해도 도로명으로 들어오도록 함)
API 재호출을 시키기 위한 trigger가 필요해 isChaged 변수를 새로 두었습니다. 팝업창에서 axios가 호출되므로 set 함수를 전달할 수 없어 postMessageAPI를 데이터 전달 용도가 아닌 isChanged를 변화시키는 수단으로 변경했습니다. 삭제는 팝업이 아닌 컴포넌트에서 진행되므로 컴포넌트로 set 함수를 전달하여  @변경시켜주었습니다.
해당 값이 true가 될 때 API 호출 시켜주었습니다. 이에 따라 초기화로만 사용되지 않아 …
=> [Fix] 배송지 추가/수정/삭제 시 API 재호출 및 수정 페이지 데이터 소멸 오류 해결

dutchiepay/src/app/_components/_layout/Header.jsx, dutchiepay/src/app/_components/_mypage/DeliveryAddress.jsx
fix/mypage-logout -> main 
1. /info 페이지 렌더링 시마다 /delivery 호출되는 오류 수정
/info 페이지에서 배송지 추가/수정이 아닌 메시지를 수신 받을 때에도 isChaged를 true로 변경하고 있어 잘못 작성된 조건식을 수정했습니다.
2. 마이페이지 로그아웃 시 addresses가 null이 되지 않는 오류 수정
마이페이지 로그아웃 시도 -> null
마이페이지에서 로그아웃 시 fetchDelivery가 addresses가 null이 됨과 동시에 재호출되어 null 처리 이후 새롭게 호출된 값으로 덮어쓰기 되고 있는 오류가 존재했습니다. 해당 오류  해결을 위해서 addresses가 null이 되기 위해서는 pathname이 "/"이 되었을 때 진행되어야 했습니다. 이에 따라 pathname이 "/"이고 로그인 상태가 아니면서 addresses에 값이 존재할 때는 null로 변경 시켜주었습니다.
=> [fix] 마이페이지에서 로그아웃 시 addresses가 null이 되지 않는 오류 수정

dutchiepay/next.config.mjs
fix/image-domains-deprecated -> main
1. The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead. 해당 오류로 인해 remotePatterns 형식으로 변경
2. hostname에 환경변수가 들어갈 수 없다고 해 환경변수를 따로 빼주었습니다.
=> [chore] image domains deprecated 관련 수정

dutchiepay/src/app/_components/_user/SocialLogin.jsx, dutchiepay/src/app/_components/_user/SocialSignup.jsx
fix/oauth-decryption -> main
1. 소셜 로그인 시 복호화 오류가 발생하지 않도록 복호화 방식을 수정했습니다.
2. JSON 형식으로 전달하는 과정 중 오류가 있어 해당 데이터를 문자열 형태로 전달받도록 수정했습니다.
3. 문자열 형태로 전달된 값을 처리하여 필요한 값이 저장되어 있는 배열로 변환했습니다. 해당 값을 로그인 정보에 저장시켜주었습니다. 이때 형변환이 필요한 userId, isCertified는 형변환을 진행했고, profileImage가 "null"인 경우 null로 저장되도록 해주었습니다.
=> [fix] 소셜 로그인 복호화 오류 해결

dutchiepay/next.config.mjs, dutchiepay/src/app/(routes)/extra-info/page.jsx, dutchiepay/src/app/layoutClient.js
feat/access-control-by-certification -> main
1. layoutClient.js에서 useSelector로 isLoggedIn과 isCertified를 가져오는 부분이 Provider 안에서 호출되도록 하기 위해 LayoutWrapper라는 하위 컴포넌트를 추가해주었습니다.
2. isLoggedIn이 true이고 isCertified가 false인 회원에 한해 /extra-info 이외의 pathname을 가진 곳에서는 /extra-info로 이동되게 해 접근을 차단해주었습니다. 
3. addInfo 폴더를 대문자가 URL에 포함되어 있고 추가 정보라는 의미와 다소 다르다고 생각되어 extra-info로 변경했습니다.
4. up/down 버튼과 floating 버튼이 extra-info에서는 표시되지 않고 header가 존재하기 때문에 로고가 불필요하다고 생각되어 로고를 삭제하고 추가 정보 페이지임을 나타내는 title을 조금 더 크게 표시해주었습니다.
현재 merge되지 않은 소셜 로그인 내용이 포함되어 해당 코드만으로는 정상적으로 동작하지 않습니다.
oauth-decryprtion branch에서 해당 코드를 추가하여 수정했을 때 문제 없이 동작했음을 확인했습니다. 로그아웃 시, 해당 조건들에서 벗어나고 main으로 자동으로 이동되기 때문에 흐름에 문제없이 동작하고 있습니다. 
처음 router.push로 구현했으나 redirect가 조금 더 명확한 의미를 가질 수 있을 것 같고, redirecct는 히스토리를 남기지 않는다고 해서 불필요한 히스토리가 생기지 않기 위해 …
=> [Feat] 휴대폰 미인증 회원 접근 제한

dutchiepay/src/app/(modals)/delivery-address/page.jsx, dutchiepay/src/app/(routes)/extra-info/page.jsx, dutchiepay/src/app/_components/_layout/Header.jsx, dutchiepay/src/app/_components/_mypage/DeliveryAddressItem.jsx, dutchiepay/src/app/layoutClient.js
fix/default-address -> main
1. 배송지 삭제 API URL 오타 수정 -> 현재 배송지 삭제 API가 수정 중이라 동작되지 않을 수 있습니다.
2. 기본 배송지를 일반 배송지로 수정하는 경우, 기본 배송지 1개를 유지하기 위해 사용자에게 안내 후, isDefault를 기존값으로 전달
3. 일반 배송지를 수정 창을 이용하지 않고 버튼을 이용해 기본 배송지로 변경할 수 있도록 버튼 추가
기본 배송지가 아닐 경우, 기본 배송지로 설정 버튼이 표시 -> confirm을 통해 변경 여부 체크 -> 해당 주소지를 isDefault를 true로 수정하는 API 호출 -> API에 의해 기존 기본 배송지는 일반 배송지로 해당 배송지는 기본 배송지로 변경
기본 배송지를 일반 배송지로 변경하였을 때 confirm을 통해 수정되지 않음을 안내 -> 확인 시,  isDefault를 true로 변경해 수정 API를 호출
기본 배송지를 일반 배송지로 수정할 수 없게 되면서 사용자에게 기본 배송지로 설정하기 위해서는 수정 팝업을 거쳐야 했습니다. 다만, isDefault만 변경되는 부분이기 때문에 같은 동작이더라도 불필요한 과정을 줄이고 사용성을 높이고자 해당 부분만 수정되는 버튼을 추가해주었습니다. 실제 동작은 동일하게 진행됩니다.
=> [feat] 기본 배송지를 일반 배송지로 변경 시 처리 및 기본 배송지 변경 버튼 추가

dutchiepay/src/app/(routes)/mypage/info/page.jsx, dutchiepay/src/app/(routes)/mypage/like/page.jsx, dutchiepay/src/app/(routes)/mypage/myask/page.jsx, dutchiepay/src/app/(routes)/mypage/mycoupon/page.jsx, dutchiepay/src/app/(routes)/mypage/myorder/page.jsx, dutchiepay/src/app/(routes)/mypage/mypost/page.jsx, dutchiepay/src/app/(routes)/mypage/myreview/page.jsx, dutchiepay/src/app/_components/_layout/Sidebar.jsx
design/mypage-ui -> main
1. 쿠폰 수와 공구 진행 수가 삭제됨에 따라 하단 여백을 조금 제거하고 page의 padding과 맞추기 위해 영역을 일부 아래로 이동
2. /mypage 내 페이지의 description이 부족하다고 생각되어 title 밑에 description을 추가했습니다.
추가 수정 사항 : sidebar의 Link가 li의 padding으로 인해 실제 표시되는 영역보다 클릭 가능 범위가 작아 클릭이 제대로 되지 않고 있습니다. 
li의 padding을 제거하고 Link로 padding을 추가하는 방식으로 수정 예정
=> [Design] mypage UI 수정

dutchiepay/src/app/(modals)/delivery-address/page.jsx, dutchiepay/src/app/(routes)/mypage/info/page.jsx, dutchiepay/src/app/_components/_layout/Header.jsx
fix/mypage-info
1. header 프로필 버튼 클릭 시 cursor 효과 추가
2. 지역 변경 시 API 호출
3. 닉네임 수정 시 값이 지워지지 않는 오류 수정
4. 프로필 삭제 클릭 시 바로 반영되지 않도록 변경
5. 주소지 추가/수정 시 필수 값 입력하지 않았을 경우 alert 추가
프로필 삭제 시에 해당 데이터를 null로 처리해야 추후 기본 프로필로 표시할 수 있으나 현재 null로 프로필 이미지를 변경 시 오류가 있어 백엔드에 오류 사항 전달했습니다. 방법이 변경되면  수정하겠습니다.
=> [Fix] mypage 관련 오류 수정

dutchiepay/src/app/(modals)/change-number/page.jsx, dutchiepay/src/app/(modals)/delivery-address/page.jsx, dutchiepay/src/app/_components/_commerce/Orderer.jsx, dutchiepay/src/app/_components/_user/FindSubmit.jsx, dutchiepay/src/app/_components/_user/PhoneAuth.jsx, dutchiepay/src/app/_components/_user/SignUpSubmit.jsx
feat/phone-hypen-remove
휴대폰 번호 입력 input에 - 입력 시 제거되도록 추가
생략
number만 입력되므로 type을 number형으로 구현했었지만, "-"은 number 형에서도 입력이 가능하긴 하지만, 해당 값을 제거하면 모든 문자열이 다 지워질 수 있다고 합니다. 그래서 text type으로 변경해 [0-9] 외에 값들은 제거되도록 수정했습니다.
휴대폰을 입력하는 페이지에 최대한 추가했으나 누락됐을 수 있습니다. 또한 Orderer에서는 현재 form이 구현되지 않아 추후 form 구현시 추가하도록 주석으로 표시해두었습니다.
=> [feat] 휴대폰 번호 입력 시 하이픈(-) 무시

dutchiepay/src/app/(routes)/login/page.jsx, dutchiepay/src/app/(routes)/signup/page.jsx, dutchiepay/src/app/_components/_user/SocialSignup.jsx, dutchiepay/src/app/_components/_user/_login/LastLogin.jsx, dutchiepay/src/app/_components/_user/_login/LoginButton.jsx, dutchiepay/src/app/_components/_user/_login/LoginInput.jsx, dutchiepay/src/app/_components/_user/_login/LoginSubmit.jsx, dutchiepay/src/app/_components/_user/_login/RememberMe.jsx, dutchiepay/src/app/_components/_user/_login/SocialButton.jsx, dutchiepay/src/app/_components/_user/_login/SocialLogin.jsx
refactor/split-login -> main
1. _component의 하위 폴더 _login을 생성해 로그인과 관련된 컴포넌트를 묶어두었습니다.
2. loginSubmit을 input / 자동로그인&아이디 찾기 / 로그인&회원가입으로 분리했습니다.
3. SocialLogin 재사용이 가능하도록 컴포넌트를 분리했습니다.
기존과 동일하게 동작합니다.
이미지 경로로 인해 폴더 정리가 어려워지는 것 같아 리팩토링 과정을 진행하면서 경로를 절대경로로 수정하려고 합니다. 추후 이미지를 import 하실 때에도 절대경로로 사용해주시면 됩니다.
=> [refactor] 로그인 컴포넌트 분리

dutchiepay/src/app/hooks/useReissueToken.jsx
ex) refactor/reissueToken -> main
useReissueToken 호출 시 access 저장 못하는 버그 수정, 내부에서 refresh token 불러오게 수정
정상적으로 새로운 토큰 발급됩니다.
=> [refactor] useReissueToken 내부에서 refresh 불러오게 수정

dutchiepay/src/app/(routes)/mypage/info/page.jsx, dutchiepay/src/app/_components/_layout/Header.jsx, dutchiepay/src/app/_components/_layout/Sidebar.jsx, dutchiepay/src/app/_components/_mypage/AccountInfo.jsx, dutchiepay/src/app/_components/_mypage/_modify/ModifyLocation.jsx, dutchiepay/src/app/_components/_mypage/_modify/ModifyNickname.jsx, dutchiepay/src/app/_components/_mypage/_modify/ModifyNumber.jsx, dutchiepay/src/app/_components/_mypage/_modify/ModifyProfileImg.jsx, dutchiepay/src/app/_components/_mypage/_modify/ProfileImgButton.jsx
refactor/split-info
1. 변경과 관련된 컴포넌트들을 _mypage 내 _modify 폴더로 한 곳에 두었습니다.
2. 각 article을 컴포넌트로 분리했습니다. 이에 따라 modifyType이 불필요해져 해당 변수는 제거하였습니다. -> modifyInfo 또한 컴포넌트 내에 별도로 관리되도록 수정할  수 있으나 user와는 달리 props로 전달되는 것이 많지 않고 props drilling이 거의 발생하지 않아 현재는 하지 않았습니다.
3.  axios 오류 시 불필요하게 modifyInfo를 다시 덮어쓰지 않아도 값이 유지되고 있어 해당 코드를 제거했습니다.
4. 지역 변경 시 기존과 동일할 경우 alert를 통해 변경될 사항이 없음을 알려주고 axios를 호출하지 않도록 하였습니다.
5. location 변수가 중복 사용되어 유지보수를 위해 새로운 location을 newLocation으로 변경했습니다.
6. 프로필 이미지의 비율이 원본 비율을 유지하지 않아 fill + cover 속성을 추가해주었습니다.
기존과 동일하게 작동합니다.
컴포넌트를 유지보수를 위해 분리하였으나 현재 모든 컴포넌트가 동시에 렌더링되고 있어 성능저하가 발생하게 됩니다. Pre-fetching과 Lazy Loading을 이용하면 이전보다 더 좋은 성능을 보일 것으로 보입니다. 다만, 해당 부분까지 진행하기에는 이미 유저 기능 구현 자체는 끝난 상황이기에 추후 리팩토링으로 보완하는 쪽으로 생각하면 될 것 같습니다.
=> [Refactor] 회원정보 수정 컴포넌트 분리

dutchiepay/src/app/_components/_layout/Footer.jsx, dutchiepay/src/app/_components/_layout/Sidebar.jsx
fix/sidebar -> main
1. sidebar border 제거
2. sidebar가 footer를 가리지 않도록 수정
sidebar의 border가 모든 디바이스를 기준으로 sidebar와 content를 구분짓지 못하는 것 같아 sidebar와 content 사이를 구분짓지 않으려고 합니다. 다만 이에 따라 sidebar 하단이 다소 허전해질 수 있습니다.
sidebar가 최소 height를 보장받지 못하면 모든 영역이 표시되지 못하고 있습니다. 다만 특정 해상도에서는 대부분 다 표시되고 있어 해당 부분에 대해서는 협의가 필요할 것 같습니다. 일단은 UI적으로 문제가 되는 부분만 수정했습니다.
=> [fix] sidebar가 footer를 가리는 현상 수정

dutchiepay/src/app/_components/_user/Logo.jsx, dutchiepay/src/app/_components/_user/_input/ConfirmPassword.jsx, dutchiepay/src/app/_components/_user/_input/EmailInput.jsx, dutchiepay/src/app/_components/_user/_input/NicknameInput.jsx, dutchiepay/src/app/_components/_user/_input/PasswordInput.jsx, dutchiepay/src/app/_components/_user/_signup/SignUpSubmit.jsx
fix/validation -> main
1. 비밀번호 - 유효성 실패 && 비밀번호 확인 - 유효성 성공 상태에서 비밀번호를 비밀번호 확인과 동일한 값으로 변경할 경우, 비밀번호 확인의 유효성이 통과되지 않는 오류 수정
2. 비밀번호 - 유효성 성공 && 비밀번호 확인 - 유효성 성공 상태에서 값 하나를 변경 시에도 유효성 성공으로 표시되는 오류 수정
3. 회원가입에서 이메일과 닉네임의 유효성 성공 상태에서 각 데이터를 중복되는 값으로 변경 시 일시적으로 유효성 성공으로 표시되는 오류 수정
4. 로고 이미지의 priority 속성을 추가해 제일 먼저 렌더링될 수 있도록 설정
즉각적으로 변하는 상황이라 테스트 화면을 캡쳐하기 애매하여 생략하였습니다. 모두 발견된 오류 및 일반적인 상황에서 제대로 동작하는 것을 확인했습니다.
1. 비밀번호 확인의 유효성이 통과되지 않는 오류는 비밀번호가 변경된 뒤에 비밀번호 확인의 유효성 재검사가 진행되지 않고 있기 때문입니다. 이전에 삭제하신 trigger를 그대로 사용하면 해결되므로, 삭제된 trigger를 다시 추가해주었습니다.
2. 비밀번호 유효성이 성공한 뒤 계속 유효성이 성공으로 표시되는 이유는 border와 안내 문구 조건에 newPassword와 confirmPassword의 오류를 모두 고려하지 않기 때문입니다. confirmPassword의 유효성 오류 표시 조건에 newPassword의 error 상태를 고려하도록 조건을 추가해주었습니다.
3. 이메일과 닉네임의 값 변경 시 유효성 성공으로 표시되는 이유는 isAvaliable 값이 값이 변경될 때 …
=> [Fix] validation 오류 수정 및 user 관련 페이지 logo warning 해결

dutchiepay/src/app/(modals)/delivery-address/page.jsx, dutchiepay/src/app/_components/_commerce/Orderer.jsx, dutchiepay/src/app/hooks/useGetPostCode.jsx
refactor/postcode -> main
1. 중복돼서 사용되던 우편번호 불러오기 코드를 custom hooks로 변경해 중복되지 않도록 변경
기존과 동일하게 동작합니다.
현재 우편번호를 사용하는 페이지가 배송지 수정/추가, 주문 페이지에서 사용되고 있는데 두 군데에서 사용하는 값 (우편번호, 도로명주소)는 동일하지만 해당 값을 저장하는 방식이 다릅니다. 한 곳은 useState의 set 함수에 저장하고 한 곳은 react hook form에 setValue를 사용하고 있습니다. 그러다보니 onComplete 이후 내용을 하나로 통일하기가 어려워 필요한 값을 반환하는 식으로 사용했습니다.
값을 반환하기 때문에 custom hooks이 아닌 util 함수로 구현하려고 했으나 우편번호를 불러오는 useDaumPostcodePopup 자체가 React Hook이기 때문에 컴포넌트 또는 커스텀 훅 내부에 호출되어야 해서 custom hooks으로 구현하는 식으로 결정했습니다. 코드가 짧아지는 이점은 없으나 중복된 코드를 줄인다는 점에서 변경하게 됐습니다.
=> [refactor] 우편번호 불러오기 함수를 custom hooks로 변경

dutchiepay/src/app/_components/_layout/Header.jsx, dutchiepay/src/app/_components/_layout/HeaderMain.jsx, dutchiepay/src/app/_components/_layout/Nav.jsx, dutchiepay/src/app/_components/_user/_login/LoginSubmit.jsx, dutchiepay/src/app/hooks/useLogout.jsx, dutchiepay/src/app/hooks/useRelogin.jsx
fix/tab-data-sharing -> main
1. 같은 브라우저 내에 다른 탭에서 페이지 접근 시 sessionStorage 데이터를 전달
2. 여러 탭 활성화 상태에서 로그아웃 시 로그아웃 storage event를 발생시켜 로그아웃 후 데이터를 덮어쓰지 않도록 수정
3. relogin 발동 조건이 sessionStorage 데이터 전달과 동시에 발생되지 않도록 로그인/로그아웃 시 dutchie-rememberMe를 localStorage에 저장시켜 자동로그인을 설정한 사용자를 구분짓도록 수정
실시간으로 변경되는 데이터라 테스트 결과는 생략하였습니다.
테스트 진행 상황
1. A 탭에서 로그인 후 B 탭으로 더취페이 접속 -> B 탭에 A 탭의 정보가 전달 됨
2. 1번 상황 이후 A 탭에서 로그아웃 -> B탭 로그아웃 처리
3. A 탭에서 자동로그인 후 B 탭으로 더취페이 접속 -> relogin 호출 (현재 relogin API가 수정 중이라 error를 반환합니다.)
여러 탭에서 같은 데이터를 사용하지만 본질적으로 같은 데이터가 아닙니다. 추후 sessionStorage에 저장되는 다른 데이터들이 많아진다면 해당 데이터들도 동기화시켜주는 작업을 거쳐야 합니다. (현재도 **delivery 동기화 문제**가 남아있습니다만, delivery 외에 다른 데이터들이 추가되지 않는다면, **delivery를 동기화 시켜주는 변수를 추가**하는 식으로 해결이 가능할 것 같습니다. 다만, 2개 이상이 되면 local에 저장되는 불필요한 trigger들이 많아질 것 같아 일단은 다른 방법도 찾아보고 …
=> [fix] 같은 브라우저 탭 내에서 session 데이터 공유되지 않는 오류 해결

dutchiepay/src/app/(routes)/commerce/[id]/page.jsx, dutchiepay/src/app/(routes)/commerce/page.jsx, dutchiepay/src/app/_components/_commerce/_product/ProductList.jsx, dutchiepay/src/app/_components/_commerce/_productDetail/ProductTitle.jsx, dutchiepay/src/app/_util/getRemainingTime.js, dutchiepay/src/app/_util/getStarRates.js
feat/nonuser-fetch-data
1. 상품 리스트와 상세페이지 API를 회원/비회원 상관없이 호출 가능하도록 변경
2. 상품의 남은 시간을 00시 00분 00초가 아닌 23시 59분 59초로 변경했습니다.
3. 별점 반환 값이 제대로 되지 않는 오류를 수정했습니다.
4. 카테고리 폰트 사이즈 변경
비회원도 정상적으로 데이터 호출됩니다.
상품 남은 시간이 년-월-일만 전달되어 00시 00분 00초를 기준으로 구현했으나 상품 리스트와 상세페이지에서 남은 시간을 다르게 표시해 수정했습니다.
=> [Feat] 비회원 상품 리스트, 상세페이지 API 호출 구현 및 남은 시간 기준 시간 변경

dutchiepay/package-lock.json, dutchiepay/package.json, dutchiepay/src/app/(routes)/order/page.jsx, dutchiepay/src/app/(routes)/order/success/page.jsx, dutchiepay/src/app/_components/_commerce/_order/Payment.jsx, dutchiepay/src/app/_components/_commerce/_order/PaymentChoice.jsx, dutchiepay/src/app/_util/constants.js, dutchiepay/src/styles/commerce.css
feat/kakao-pay -> main
1. 커스텀 배송 메세지 처리 및 배송 메세지 상수화
2. 카카오페이 결제 요청 시 카카오 결제 요청 API 호출
3. 결제 요청 반환 값으로 redirect
4. postMessage를 통해 백엔드로부터 결제 결과 반환 및 성공 시 /success 페이지로 리다이렉트
5. /success 페이지 URL orderid 쿼리 추가
6. quantity가 문자열로 전달되는 오류 해결
현재 해당 API가 동작되지 않아 테스트는 생략하였습니다.
백엔드 결제 연동 테스트를 위해 코드 분리 없이 진행했습니다. 추후 컴포넌트 별도로 나눌 예정입니다.
=> [feat] 카카오페이 결제 요청 API 및 결제 상태 message 처리

dutchiepay/src/app/(modals)/withdraw-auth/page.jsx, dutchiepay/src/app/_components/_commerce/_product/ProductLike.jsx, dutchiepay/src/app/_components/_mypage/Withdraw.jsx
- [] 기능 추가
fix/withdraw-logout -> main
1. 회원탈퇴 시 useLogout이 아닌 별도 로그아웃처리를 진행해 로그아웃 API를 호출하지 않도록 변경
2. /auth-phone을 탈퇴용 핸드폰 인증 페이지임을 명확히 할 수 있도록 /withdraw-auth로 변경
3. 인증 완료 후 탈퇴 시 전달되는 message를 로그아웃이 아닌 회원탈퇴임을 명확히 함
4. 상품 좋아요 API 호출되도록 주석 해제
=> [fix] 회원탈퇴 시 로그아웃 API 호출하지 않고 로그인 정보 초기화하도록 변경

dutchiepay/src/app/_components/_commerce/_productDetail/OrderButton.jsx, dutchiepay/src/app/_components/_commerce/_productDetail/Quantity.jsx
fix/quantity-input -> main
1. 수량 입력 시 빈 문자열도 입력 가능하도록 수정
2. 수량이 빈 문자열일 경우, 회원이 구매 버튼 클릭 시 alert 표시 (비회원은 로그인 페이지)
3. 수량이 99개를 넘을 경우 alert
=> [fix] 수량 입력 시 빈 문자열도 입력 가능하도록 수정

dutchiepay/src/app/_util/getFormatDate.js
fix/timezone -> main
UTC 형태로 변환되던 마감 기한을 KST 형식으로 지정한 뒤 시간을 계산하도록 수정했습니다.
=> [fix] 마감 기한을 KST로 계산하도록 수정

dutchiepay/src/app/_components/_layout/Header.jsx, dutchiepay/src/app/_components/_layout/HeaderMain.jsx, dutchiepay/src/app/layoutClient.jsx
fix/userinfo-tab-sharing -> main
1. 탭간 정보 공유와 재로그인 코드를 layout에서 실행하여 다른 페이지 및 팝업에서도 유저정보를 가질 수 있도록 변경
팝업에서 수정/추가 등 작업 정상적으로 가능
가끔씩 main 페이지에서 오류가 발생했습니다가 뜨는 경우가 있는데 main 내의 fetch 문제인 걸로 확인됐으나 서버 문제는 아니고 일시적인 문제거나 프론트 문제일 것 같습니다. 현재는 해당 오류가 발생하지 않지만, 혹여나 main에서 오류 발생할 경우 알려주세요
=> [fix] BroadcastChannel 및 relogin layout에서 실행되도록 수정

dutchiepay/src/app/(routes)/mypage/myorder/page.jsx, dutchiepay/src/app/_components/_commerce/_refund/RefundForm.jsx, dutchiepay/src/app/_util/constants.js
fix/exchange-refresh -> main
1. 환불/교환 요청 시 refresh가 되도록 hasFetched.current = false; 설정
2. 환불/교환 요청 시 refresh를 할 경우 페이지를 1로 호출
정상적으로 refresh 됩니다. (환불 가능한 상품이 더 없어서 이미지는 생략합니다.)
loadmore 코드가 page를 1씩 증가하는 코드이다보니 페이지가 1일 때는 제외하고는 같은 페이지를 호출해도 order 배열에 추가해버리게 됩니다. 그럴 경우 refresh를 하게 되면 해당 부분 구매 내역이 중복이 되기 때문에 로직을 완전히 수정하기에는 시간 문제가 있을 것 같아서 페이지 1 (초기화) 하는 방식으로 작업했습니다. 환불 요청 시 바로 팝업창이 닫기면서 수정되기 때문에 조금 더 자연스럽게 하기 위해 alert로 정상 처리 됐음을 알리는 과정을 추가했습니다
=> [fix] 환불 요청 시 refresh 되지 않는 오류 해결

dutchiepay/src/app/(routes)/mypage/myorder/page.jsx, dutchiepay/src/app/_components/_commerce/ProductLike.jsx, dutchiepay/src/app/_components/_commerce/_refund/RefundForm.jsx, dutchiepay/src/app/_util/constants.js
fix/like-rendering -> main
productId가 변경될 때마다 isLiked 여부를 다시 체크하도록 수정했습니다.
좋아요 상품 모두 reset 한 상태
해당 상품 좋아요를 누르고 필터 변경 후, 좋아요 누른 상품에만 좋아요 표시되고 기존에 좋아요한 위치에는 표시되지 않음
=> [Fix] 상품 목록에서 좋아요를 누를 경우 필터링을 바꾸면 해당 위치 상품이 isLiked와 상관없이 좋아요 표시되는 오류

dutchiepay/src/app/(routes)/community/detail/page.jsx, dutchiepay/src/app/(routes)/mart/detail/page.jsx, dutchiepay/src/app/(routes)/used/detail/page.jsx, dutchiepay/src/app/_components/_community/PostDetail.jsx
fix/mart-post -> main
postDetail을 fixed에서 sticky로 변경하고 post 레이아웃을 flex 효과를 추가해 해상도 변경 시에도 PostDetail을 고정시키고 스크롤 시에도 해당 영역이 항상 보일 수 있도록 수정했습니다.
해상도를 줄여도 postDetail 고정
content 길이가 무한히 길어져도 우측 영역은 항상 보이도록 설정
이와 유사한 방식으로 sidebar도 해결될 수 있을 것으로 보여 추후 수정 진행하겠습니다
=> [fix] PostDetail sticky로 고정

dutchiepay/package-lock.json, dutchiepay/package.json, dutchiepay/src/app/(routes)/community/write/page.jsx, dutchiepay/src/app/(routes)/location/page.jsx, dutchiepay/src/app/(routes)/mart/write/page.jsx, dutchiepay/src/app/(routes)/used/write/page.jsx, dutchiepay/src/app/_components/_community/TextEditor.jsx, dutchiepay/src/app/_components/_community/_post/CommunityFilter.jsx, dutchiepay/src/app/_components/_community/_post/DateInput.jsx, dutchiepay/src/app/_components/_community/_post/HeadCount.jsx, dutchiepay/src/app/_components/_community/_post/MeetingPlaceInput.jsx, dutchiepay/src/app/_components/_community/_post/PostWritingAction.jsx, dutchiepay/src/app/_components/_community/_post/TextEditor.jsx, dutchiepay/src/app/_components/_community/_post/TitleInput.jsx, dutchiepay/src/app/_components/_community/_post/UploadedImages.jsx, dutchiepay/src/styles/community.css
feat/post-write -> main
1. 게시글 form을 react hook form으로 연결
2. 날짜와 시간 모두 입력될 경우, formattedDateTime을 formData에 추가하여 API 전달 형식 구현 -> 해당 형식 반환 함수는 마트/배달에서만 사용해 재사용 가능성이 없다고 판단되어 util로 구분해두지는 않았으나 추후 코드가 길어질 때에는 분류할 예정입니다.
3. 게시글 관련 컴포넌트 분리
4. react quill에서 게시글 내용이 container 영역 이상으로 커질 경우, toolbar가 사라지는 오류 해결
5. content 내용이 editor보다 길어질 경우, toolbar와 겹쳐보이는 오류 해결
6. 업로드 이미지 컴포넌트를 별도로 분리하여 관리하도록 설정
7. 이미지 업로드 핸들러를 사용하여 이미지를 서버에 업로드 한 뒤 업로드하도록 설정 -> 이미지 업로드 함수를 getImage 함수를 사용해 gif 파일 업로드가 불가능합니다. 추후 getImage 함수를 수정해 gif 파일 업로드가 가능하도록 변경할 예정입니다.
8. 이미지 업로드 시 images 배열에 추가하고, 게시글에서 제거 시 images 배열에서도 삭제되도록 구현
9. 최초 이미지 업로드 시 대표 이미지 설정
10. 이미지 목록에서 이미지를 클릭할 경우, 대표 이미지로 설정
11. 이미지 목록 내에서 이미지 X 버튼을 클릭 할 시 게시글 내에서도 이미지가 제거되도록 구현, 대표 사진일 경우 이미지가 삭제되지 않도록 설정 -> 이 경우, 게시글 내에서 이미지를 삭제할 경우 문제가 되어 게시글 내에서 …
=> [Feat] 게시글 작성 form 구현 및 react quill 에디터 기능 추가

dutchiepay/package-lock.json, dutchiepay/package.json, dutchiepay/src/app/(routes)/community/[id]/page.jsx, dutchiepay/src/app/(routes)/community/page.jsx, dutchiepay/src/app/(routes)/community/write/[id]/page.jsx, dutchiepay/src/app/(routes)/community/write/page.jsx, dutchiepay/src/app/(routes)/mart/detail/page.jsx, dutchiepay/src/app/(routes)/mart/write/page.jsx, dutchiepay/src/app/(routes)/used/detail/page.jsx, dutchiepay/src/app/_components/_community/PostContent.jsx, dutchiepay/src/app/_components/_community/_common/PostContent.jsx, dutchiepay/src/app/_components/_community/_common/PostDetailAction.jsx, dutchiepay/src/app/_components/_community/_common/TextEditor.jsx, dutchiepay/src/app/_components/_community/_free/Comment.jsx, dutchiepay/src/app/_components/_community/_free/CommentForm.jsx, dutchiepay/src/app/_components/_community/_free/FreePostForm.jsx, dutchiepay/src/app/_components/_community/_free/Post_Hot.jsx, dutchiepay/src/app/_components/_community/_free/Post_Similar.jsx, dutchiepay/src/app/_components/_community/_local/CurrentPost.jsx, dutchiepay/src/app/_util/getFormatDate.js, dutchiepay/src/app/hooks/useFetchUpdatePostData.jsx
feat/mart-write-api -> main
1. 커뮤니티 상세페이지 동적 라우팅으로 변경
2. 상세페이지 접근 시 상세페이지 API 호출 및 데이터 바인딩
3. HTML 렌더링 과정 중 XSS 공격 방지를 위해 dompurity 적용
4. PostContent를 지역/자유 게시판 모두 활용할 수 있고 변경된 API에 맞춰 수정
5. 게시글 수정 및 삭제 actions 처리
6. 수정 페이지 접근 시 게시글 데이터를 받아올 수 있는 custom hook을 구현, 지역/자유 게시판 모두 가능하도록 처리
7. 자유게시판 수정 페이지 접근 시 form 데이터 set 처리
8. content 수정 값 set을 위해 react quill value 설정
9. 게시글 작성 시간 표시를 위한 getPostDate 추가 -> 추후 게시글 작성 시 사용되는 함수와 통합 PR 올릴 예정
10.
=> [Feat] 자유게시판 게시글 작성, 수정, 삭제 구현

dutchiepay/src/app/(routes)/community/page.jsx, dutchiepay/src/app/(routes)/mart/page.jsx, dutchiepay/src/app/(routes)/search/page.jsx, dutchiepay/src/app/_components/Product.jsx, dutchiepay/src/app/_components/_community/CommunityPostList.jsx, dutchiepay/src/app/_components/_community/_common/PostContent.jsx, dutchiepay/src/app/_components/_community/_common/PostSearch.jsx, dutchiepay/src/app/_components/_community/_free/CommentForm.jsx, dutchiepay/src/app/_components/_community/_free/CommentWrite.jsx, dutchiepay/src/app/_components/_community/_free/FreeCommentList.jsx, dutchiepay/src/app/_components/_community/_local/MartPostList.jsx, dutchiepay/src/app/_components/_layout/Header.jsx, dutchiepay/src/app/_components/_layout/HeaderTop.jsx, dutchiepay/src/app/_components/_search/SearchContainer.jsx, dutchiepay/src/app/hooks/useInfiniteScroll.jsx
fix/search-list -> main
1. 상품 검색 결과 출력
2. 검색 결과 컴포넌트 Image 요소에 의한 z-index 변경
3. 커뮤니티 검색을 위해 PostSearch 구현
※ 현재 API 명세서와 가격 변수명이 달라 수정 요청 드렸습니다. (이전 컴포넌트 재사용이라 다른 API와 변수명이 달라서 백엔드에서 변경해야 함)
※ 해당 이미지에서 검색어 없음으로 표시되는 이유는 현재 ""가 전달될 경우, 모든 값이 반환되고 있어서 수정 요청드렸습니다. 필터링 체크를 위해 해당 출력으로 테스트했고 프론트에서도 검색어가 ""일 경우에는 검색결과 없음이 표시되도록 작업해두었습니다.
onChange마다 요청이 들어가도록 설정되었습니다. 무한스크롤 자체 구현이 그렇게 설정되어 있어서 해당 부분 성능 강화를 위해서는 onChange 시에 바로바로 set되는 것이 아닌 디바운스로 일정 시간 뒤에 set되도록 설정해주면 되나 별도 라이브러리가 필요하고 현재 기능 동작 구현이 우선이라 생각해서 추후 필요하다고 판단되면 추가할 예정입니다.
=> [Feat] 상품/커뮤니티 검색 목록 

dutchiepay/src/app/_components/_community/_common/TextEditor.jsx, dutchiepay/src/app/_util/getBase64File.js
feat/paste-image -> main
붙여넣기한 이미지를 base64에서 File 객체로 변환한 뒤, S3에 업로드 하여 반환된 URL로 대치
붙여넣기한 이미지 이미지 목록에 사용 가능
이전에 회의에서 붙여넣기한 이미지를 사용하지 않도록 하고자 하였으나 사용성이 너무 떨어질 것 같고, React quill에서 이미지를 base64 형식으로 이용한다고 하고 대부분의 레퍼런스에서 base64 처리만 해주는 걸로 보아 걱정했던 오류가 없을 것으로 판단했습니다.
=> [feat] 붙여넣기한 base64 이미지를 S3에 업로드하여 대체

dutchiepay/src/app/(routes)/mypage/mypost/page.jsx, dutchiepay/src/app/_components/_mypage/MyPostList.jsx
ex)  fix/mypost-UI-> main
마이페이지 활동 내역 UI description 부분 동일한 크기로 UI 수정했습니다.
html태그는 벡엔드에서 수정해서 넘겨주기로 했고 댓글 남긴 게시글 또한 API 반환값 이상으로 확인되어 벡엔드에 수정요청 드렸습니다
=> [fix] 마이페이지 활동내역 UI 수정

dutchiepay/src/app/(modals)/change-number/page.jsx, dutchiepay/src/app/(routes)/extra-info/page.jsx, dutchiepay/src/app/(routes)/used/write/[id]/page.jsx, dutchiepay/src/app/(routes)/used/write/page.jsx, dutchiepay/src/app/_components/_community/_local/PostState.jsx, dutchiepay/src/app/_components/_community/_local/TradeDetailInfo.jsx, dutchiepay/src/app/_components/_user/AddInfoSubmit.jsx, dutchiepay/src/app/_components/_user/_phone/AuthCode.jsx, dutchiepay/src/app/_components/_user/_phone/PhoneInput.jsx, dutchiepay/src/app/hooks/useFetchDelivery.jsx
1. 나눔/거래 카테고리에 따라 state를 다르게 설정하도록 변경
- 나눔/거래 상태 : 대기중, 거래중, 나눔완료, 거래완료
2. 나눔 상품일 경우, 게시글 상세페이지에서 나눔 상품으로 표시되도록 변경
3. 거래 상품일 경우, 게시글 상세페이지에서 가격에 콤마(,)를 붙이도록 변경
4. 나눔/거래 게시글 수정 시 price 값이 string 형이 아닌 number형으로 set되는 오류 해결
5. 나눔 카테고리일 경우 price를 -1로 전달하도록 변경
6. 배송지 추가, 수정, 삭제 시 refresh 되지 않는 오류 해결
7. 추가 정보 입력 페이지를 protected route로 설정하고, isCertified가 true가 되면 main으로 이동하도록 변경
8. 휴대폰 인증번호 유효기간 만료 후에도 인증처리가 되지 않도록 인증번호 확인 시 남은 시간 체크하도록 추가
9. 휴대폰 변경 팝업 창에서 input 클릭 시 trigger 오류가 발생하지 않도록 trigger를 추가
10. 휴대폰 인증번호 재전송 시, alert를 추가하여 재전송됐음을 명확하게 표시
useEffect 무한 루프로 인해 hasFetch ref를 사용할 경우, 해당 코드가 refresh 되는 경우가 있는지 체크하고 그에 맞춰서 추가해주세요. 초기 fetching을 위한 코드에만 해당 코드가 유효하고 변경될 때마다 refresh 될 경우, hasFetch ref를 사용하게 되면 해당 로직에 문제가 발생합니다.
=> [Fix] test시 발견된 오류 해결

dutchiepay/src/app/_components/_alarm/AlarmActiveAction.jsx, dutchiepay/src/app/hooks/useLogin.jsx, dutchiepay/src/app/hooks/useReissueToken.jsx, dutchiepay/src/app/hooks/useRelogin.jsx
refresh token이 필요한 요청 (relogin, reissue)에 withCredentials 설정을 추가했습니다.
요청 시 쿠키가 전달됩니다.
=> [fix] refresh token이 필요한 API 요청에 쿠키 추가

dutchiepay/src/app/hooks/useRelogin.jsx
refresh token이 만료되어 자동로그인이 실패할 경우, 페이지 전환 시마다 relogin API를 호출하지 않도록 localStorage에서 rememberMe 값을 삭제해주었습니다.
=> [fix] refresh token 만료로 인한 자동로그인 실패 시 rememberMe 삭제

dutchiepay/src/app/(routes)/community/[id]/page.jsx, dutchiepay/src/app/(routes)/community/page.jsx, dutchiepay/src/app/(routes)/help/page.jsx, dutchiepay/src/app/(routes)/mart/[id]/page.jsx, dutchiepay/src/app/(routes)/mart/page.jsx, dutchiepay/src/app/(routes)/order/page.jsx, dutchiepay/src/app/(routes)/used/[id]/page.jsx, dutchiepay/src/app/(routes)/used/page.jsx, dutchiepay/src/app/_components/ProtectedRoute.jsx, dutchiepay/src/app/_components/_commerce/_productDetail/OrderButton.jsx, dutchiepay/src/app/_components/_community/_free/FreePostItem.jsx, dutchiepay/src/app/_components/_community/_local/MartPostItem.jsx, dutchiepay/src/app/_components/_community/_local/TradePostItem.jsx, dutchiepay/src/app/_components/_layout/HeaderTop.jsx, dutchiepay/src/app/_components/_user/_login/LoginSubmit.jsx, dutchiepay/src/app/hooks/useOauthLogin.jsx
feat/login-redirect -> main
로그인 시 메인페이지가 아닌 이전 페이지로 redirect가 가능하도록 login URL에 redirect query를 추가하였습니다.
Protected Route로 인해 비회원이 게시글 상세페이지를 접근할 경우 로그인되는 로직 중 게시글 상세페이지 내 fetch 코드가 먼저 동작하여 오류 반환 후 상세페이지로 이동되는 오류를 비회원일 경우 fetch를 진행하지 않도록 변경하여 해결
소셜 로그인 동작 여부는 배포 후 테스트가 가능하여 생략
=> [feat] 로그인 시 이전 페이지로 redirect

dutchiepay/src/app/_util/getLocation.js, dutchiepay/src/app/api/map-reversegeocode/route.js
fix/security -> main
reversegeocoding을 클라이언트 단에서 호출하여 API 키가 노출되어 API routes로 호출 방식을 변경하였습니다.
localhost를 서비스 URL에서 제거하기 전까지는 동작하는 걸 확인했으나 URL을 제거하여 배포 서비스에서만 동작을 확인할 수 있어 배포 후문제 체크하겠습니다.
payment와 map 렌더링 API 호출 시 키가 노출되어 해당 부분 수정하려고 하였으나 SDK는 클라이언트 단에서만 동작하여 API routes를 이용할 수 없고 지도 렌더링는 client_id를 노출시키지 않을 방법이 없다고 하여 localhost를 제거하는 방향으로 1차 처리하려고 합니다. 이후 방법을 찾게 되면 해당 부분 수정할 예정입니다. 일단 가장 문제가 되는 부분부터 처리하여 PR 올립니다.
=> [fix] API routes를 이용하여 reversegeocoding 호출
