DutchiePay/DutchiePay-Front

- dutchiepay/next.config.mjs
- dutchiepay/src/middleware.js
ex) fix/redirect-static -> main
정적 배포를 위해 middleware.js 파일을 삭제하고 next.config.js 설정 변경
정상적으로 마이페이지 접속 가능
> [fix] 정적 배포를 위한 middleware 삭제, next.config.js에서 리다이렉션 설정

- dutchiepay/src/app/(modals)/change-number/page.jsx
- dutchiepay/src/app/(routes)/mypage/info/page.jsx
- dutchiepay/src/app/_components/_user/PhoneAuth.jsx
- dutchiepay/src/app/layoutClient.js
feat/change-phone-number -> main
1. 휴대폰 번경 페이지 추가 (UI는 기능 구현을 위해 추후 수정될 예정입니다.)
2. redux의 isLoggedIn과 access 값  여부에 따라 접근 제한 -> 현재 reissue, 자동로그인 API가 구현되지 않아 해당 부분은 현재는 비회원이 접근 가능하도록 주석처리 되어 있습니다.
3. 휴대폰 번호 변경 API -> 인증여부 확인 후 동작이 아닌 동작 시 인증 여부 확인으로 구현되어 있습니다. (추후  수정 예정입니다.)
4. /info 페이지 휴대폰 번호 관련 코드 삭제 (type에 '전화번호'는 존재하지 않도록 관련 코드 모두 삭제했습니다.)
5. modify 변수에 전화번호 삭제 -> 페이지에서 자체 변경되어 redux로 저장되기 때문에 필요하지 않아 삭제했습니다.
빠른 merge를 위해 생략
휴대폰 번호 변경 시, redux로 저장되도록 해주시면 됩니다! 구현 위치 주석으로 표시해두었습니다.
> [Feat] 휴대폰 번호 변경

- dutchiepay/src/styles/globals.css
fix -> loading-spinner-chnage
로딩스피너 CSS를 변경
> [design] 로딩 스피너 css 변경

- dutchiepay/src/app/(routes)/addInfo/page.jsx
- dutchiepay/src/app/(routes)/login/page.jsx
- dutchiepay/src/app/(routes)/mypage/info/page.jsx
- dutchiepay/src/app/_components/_layout/Header.jsx
- dutchiepay/src/app/_components/_user/AddInfoSubmit.jsx
…게 수정
ex) feat/redirect-setting -> main
로그인시 isCertified 값에 따라 분기 처리, Header에 로그아웃 API 추가, 이미지 변경되게 수정
현재 middleware.js를 만들어 전역적으로 리다이렉트 관리를 하려했으나 구현 실패하여 일단은 route.push로 구현해 두었습니다. 
다시 찾아봐서 middleware로 구현해두겠습니다.
> [feat,fix] 로그인시 isCertified 값에 따라 분기 처리, Header에 로그아웃 API 추가, 이미지 변경되게 수정

- dutchiepay/src/app/_components/_layout/Header.jsx
ex) fix/header-logout -> main
헤더 로그아웃 에러 해결했습니다.
> [fix] 헤더 로그아웃 에러 해결

- dutchiepay/src/app/(routes)/mypage/info/page.jsx
ex) fix/user-system-info-> main
변경 API 중복 에러 뜰시  원래 값으로 수정 값 덮어씌우지 않는 오류 수정
**다시 클릭 시**
> [fix] 변경 API 오류 시, 원래 값으로 수정 값 덮어씌우지 않는 오류 수정

- dutchiepay/src/app/_components/_layout/Header.jsx
- dutchiepay/src/app/_components/_mypage/Withdraw.jsx
- dutchiepay/src/app/_components/_user/EmailInput.jsx
- dutchiepay/src/app/_components/_user/ResetSubmit.jsx
- dutchiepay/src/app/hooks/useLogout.jsx
ex) refactor/useLogout-> main
로그아웃 hook 생성 훅 만드니 재로그인 시 로그아웃 오류도 같이 해결됐네요 ...?
**Header.jsx**
**ResetSubmit.jsx**
> [fix] 재로그인 시 로그아웃 안 되는 오류 수정 로그아웃 hook 생성

- dutchiepay/src/app/(routes)/extra-info/page.jsx
- dutchiepay/src/app/(routes)/login/page.jsx
- dutchiepay/src/app/_components/_layout/Header.jsx
- dutchiepay/src/app/_components/_user/FindSubmit.jsx
- dutchiepay/src/app/_components/_user/ResetSubmit.jsx
- dutchiepay/src/app/layoutClient.js
fix/error-handling -> main
1. User 도메인 error 메시지 처리
2. 실제 에러와 관계없이 에러 처리를 하던 코드 일부 수정
이 외에도 에러 추가를 했으나 에러를 발생시킬 수 있는 경우가 안 되는 에러가 있어 생략하였습니다.
> [Fix] user API 에러 처리

- dutchiepay/src/app/(modals)/change-number/page.jsx
- dutchiepay/src/app/(routes)/mypage/info/page.jsx
ex)  fix/prorile-info-error -> dev
기본 프로필 변경 시 변경 안되는 에러, 변경취소 작동안되는 에러 수정
> [fix] 프로필 기본이미지 변경 시 에러 수정

- dutchiepay/src/app/(routes)/extra-info/page.jsx
- dutchiepay/src/app/_components/_user/AddInfoSubmit.jsx
fix/addInfo -> main
일부 변경 사항 반영 되지 않은 오류 수정
불필요한 변수 생성 과정 제거
페이지 오류가 발생해 merge 하겠습니다
> [fix] 변경 사항 수정 누락 및 불필요한 변수 생성 코드 삭제

- dutchiepay/src/app/(modals)/auth-phone/page.jsx
- dutchiepay/src/app/(routes)/mypage/info/page.jsx
- dutchiepay/src/app/_components/_mypage/Withdraw.jsx
- dutchiepay/src/app/hooks/useLogout.jsx
- dutchiepay/src/app/layoutClient.js
ex) feat/auth-phone -> main
회원탈퇴 전 휴대폰 인증 진행 
> [feat] 회원탈퇴 전 휴대폰인증 추가

- dutchiepay/src/app/_components/_user/_signup/SignUpSubmit.jsx
ex) refactor/signup-error-phone-reset-> main
[refactor] 회원가입 시 중복된 전화번호 인증 시 휴대폰 input창 다시 입력가능하게 수정
> [refactor] 회원가입 시 중복된 전화번호 인증 시 휴대폰 input창 다시 입력가능하게 수정

- dutchiepay/src/app/_components/_layout/Floating.jsx
- dutchiepay/src/app/_components/_layout/UpDownButton.jsx
- dutchiepay/src/app/_components/_user/_input/ConfirmPassword.jsx
- dutchiepay/src/styles/mypage.css
ex) fix/UI-bug-> main
UI 해상도에 따른 플로팅버튼, 업다운버튼 수정했습니다
플로팅버튼, 업다운 버튼에 z-index를 추가하였고 회원가입 버튼들에 각각 background-color:white를 주어 수정했습니다.
> [fix]UI 해상도에 따른 플로팅버튼, 업다운버튼 수정

- dutchiepay/src/app/(routes)/addition/page.jsx
> [fix] 데이터 전송 시 값 초기화

- dutchiepay/src/app/_components/_commerce/ReviewItem.jsx
- dutchiepay/src/app/_components/_mypage/MyReview.jsx
- dutchiepay/src/styles/imageStyle.jsx
ex) fix/images-more-icon-> main
이미지 더보기 화살표 클릭시 이미지 더보기 아이콘도 같이 내려가는 에러 수정
> [fix] 이미지 더보기 화살표 클릭시 이미지 더보기 아이콘도 같이 내려가는 에러 수정

- dutchiepay/src/app/_components/_layout/Floating.jsx
- dutchiepay/src/app/_components/_layout/UpDownButton.jsx
ex) fix/UI-bug -> main
floating 버튼 작동 안하는 에러 수정
> [fix] floating 버튼 작동 안하는 에러 수정

- dutchiepay/__test__/(routes)/login/page.jsx
- dutchiepay/__test__/_components/_user/_login/LoginSubmit.test.jsx
- dutchiepay/jest.config.js
- dutchiepay/jest.setup.js
- dutchiepay/package-lock.json
- dutchiepay/package.json
ex) test/jest -> main
jest 설정 및 테스트
없는 이메일 비밀번호로 로그인시 테스트는 개발 마무리 되지않아 주석처리 해놨습니다.
> [feat] jest 설정 및 로그인 test

- dutchiepay/src/app/_components/_user/AddInfoSubmit.jsx
- dutchiepay/src/redux/slice/loginSlice.js
fix/isCertified -> main 
추가 정보 입력이 성공할 경우 isCertified를 true로 변경해주었습니다.
추후 추가
> [fix] 추가 정보 입력 후 isCertified 변경되지 않는 오류 수정

- dutchiepay/.eslintrc.json
- dutchiepay/package-lock.json
- dutchiepay/package.json
init/eslint -> main
1. eslint 설정을 추가했습니다. (/out 폴더는 무시하도록 설정했습니다.)
설정은 기본 값 위주로만 넣었습니다.
extension 설치해주세요
> [init] eslint 설정

- dutchiepay/.eslintrc.json
- dutchiepay/src/app/(modals)/auth-phone/page.jsx
- dutchiepay/src/app/(modals)/change-number/page.jsx
- dutchiepay/src/app/(modals)/delivery-address/page.jsx
- dutchiepay/src/app/(routes)/commerce/[id]/page.jsx
- dutchiepay/src/app/(routes)/extra-info/page.jsx
- dutchiepay/src/app/(routes)/introduction/page.jsx
- dutchiepay/src/app/(routes)/location/page.jsx
- dutchiepay/src/app/(routes)/mypage/info/page.jsx
- dutchiepay/src/app/(routes)/reset/page.jsx
- dutchiepay/src/app/_components/_commerce/_product/ProductList.jsx
- dutchiepay/src/app/_components/_commerce/_productDetail/Quantity.jsx
- dutchiepay/src/app/_components/_commerce/_productDetail/RemainingTime.jsx
- dutchiepay/src/app/_components/_layout/Sidebar.jsx
- dutchiepay/src/app/_components/_mypage/_delivery/AddressAddition.jsx
- dutchiepay/src/app/_components/_mypage/_delivery/DeliveryAddress.jsx
- dutchiepay/src/app/_components/_mypage/_modify/ModifyNumber.jsx
- dutchiepay/src/app/_components/_mypage/_modify/ProfileImgButton.jsx
- dutchiepay/src/app/_components/_rating/Rating.jsx
- dutchiepay/src/app/_components/_user/ResetSubmit.jsx
- dutchiepay/src/app/_components/_user/_find/FindSubmit.jsx
- dutchiepay/src/app/_components/_user/_input/AddressInput.jsx
- dutchiepay/src/app/_components/_user/_input/NicknameInput.jsx
- dutchiepay/src/app/_components/_user/_login/LoginSubmit.jsx
- dutchiepay/src/app/_components/_user/_phone/AuthCode.jsx
- dutchiepay/src/app/_components/_user/_phone/PhoneInput.jsx
- dutchiepay/src/app/_util/getLocation.js
- dutchiepay/src/app/_util/getStarRates.js
fix/eslint-error
eslint 추가 후 확인된 warning을 제거했습니다.
일부 warning 중 console 중에 현재 작업 중인 부분을 제외한 console을 제거했습니다.
기존과 동일하게 동작합니다.
> [fix] eslint 에러 해결

- dutchiepay/src/app/_components/_user/_phone/PhoneAuth.jsx
- dutchiepay/src/app/_components/_user/_phone/PhoneInput.jsx
- dutchiepay/src/app/_components/_user/_signup/SignUpSubmit.jsx
ex) fix/phone-auth-> dev
1. 휴대폰 번호 중복 시 input창 수정안되는 에러 수정
2. 휴대폰 번호 중복 시 input창 유효성 검사 안하는 버그 수정
> [fix] 휴대폰 중복 시 disabled 해결, 중복 시 휴대폰 input 유효성 검사 안하는 버그 수정

- dutchiepay/src/app/(routes)/mypage/like/page.jsx
- dutchiepay/src/app/(routes)/mypage/mypost/page.jsx
- dutchiepay/src/app/_components/SectionSearch.jsx
- dutchiepay/src/app/_components/_commerce/_product/ProductCategory.jsx
- dutchiepay/src/app/_components/_commerce/_product/ProductFilter.jsx
- dutchiepay/src/app/_components/_layout/Header.jsx
- dutchiepay/src/app/_components/_layout/HeaderTop.jsx
- dutchiepay/src/app/_components/_layout/Nav.jsx
- dutchiepay/src/app/_components/_layout/SearchInput.jsx
- dutchiepay/src/app/_components/_layout/Sidebar.jsx
- dutchiepay/src/app/_components/_mypage/MypageFilter.jsx
- dutchiepay/src/app/_components/_user/AddInfoSubmit.jsx
- dutchiepay/src/app/_util/constants.js
- dutchiepay/src/styles/mypage.css
refactor/filter-constant -> main 
1. Header를 HeaderTop, Nav, SearchInput 컴포넌트를 추가하여 코드를 분리해주었습니다.
2. Header Nav active 동작 코드를 간소화했습니다.
3. 필터/카테고리를 상수화하고 불필요한 중복 코드를 제거했습니다.
4. 마이페이지 내의 Filter 컴포넌트를 재사용하도록 변경했습니다.
기존과 동일하게 동작합니다.
구매내역에서의 필터는 추후 구매내역 status 값이 백엔드와 맞춰지면 수정하도록 하겠습니다.
> [Refactor] Header 컴포넌트 분리, 필터/카테고리 상수화 및 중복 코드 제거

- dutchiepay/src/app/_components/_commerce/_product/ProductCategory.jsx
fix/categories -> main
카테고리가 제대로 렌더링되지 않는 오류를 해결했습니다.
관련 처리를 해야해서 바로 merge하겠습니다.
> [fix] 카테고리가 렌더링되지 않는 오류 해결

- dutchiepay/src/app/(routes)/order/page.jsx
- dutchiepay/src/app/(routes)/order/success/page.jsx
- dutchiepay/src/app/_components/_commerce/_order/Payment.jsx
- dutchiepay/src/app/_components/_commerce/_order/PaymentChoice.jsx
- dutchiepay/src/app/_components/_layout/Header.jsx
- dutchiepay/src/app/_components/_mypage/_delivery/DeliveryAddressItem.jsx
- dutchiepay/src/app/_util/constants.js
- dutchiepay/src/app/hooks/useFetchDelivery.jsx
- dutchiepay/src/app/hooks/useLogout.jsx
- dutchiepay/src/styles/commerce.css
feat/address-tab-sharing
1. fetchAddress 과정에서 isChanged로 인한 fetch일 경우, 다른 탭으로 refetching된 주소지를 전달
2. 마이페이지 등과 같이 로그인한 회원만 접근 가능한 페이지에서 로그아웃 시 비정상적인 접근이 뜨는 오류 해결
마이페이지에서 로그아웃 시 alert 뜨지 않음
branch 이슈로 카카오페이 코드도 함께 commit 되었는데 수정 사항은 없어서 pull되면 자동으로 해결될 것 같습니다.
> [Feat] 주소지 탭 간 동기화 및 로그아웃 시 비정상접근 뜨는 오류 해결

- dutchiepay/src/app/(routes)/order/page.jsx
feat/kakao-pay -> main
1. 토스페이먼츠 결제 연동
2. 신용카드 결제 시 백엔드로 API 호출
현재 백엔드 API 동작되지 않아 "결제 실패" alert가 반환됩니다. "결제 실패" 반환 시 결제는 진행되었음을 의미하고 default alert 반환 시 결제자체에서 오류가 있음을 의미합니다.
.env 값 변경되었습니다. Slack DM 참고해주세요.
무통장 입금까지 모두 구현 시 코드 리팩토링 진행할 예정입니다.
> [feat] 토스페이먼츠 결제 구현

- dutchiepay/src/app/(modals)/images/page.jsx
> [fix] images 페이지 클라이언트 컴포넌트 변경

- dutchiepay/src/app/(routes)/used/page.jsx
fix/build-error -> main
tabindex를 tabIndex로 변경했습니다.
> [fix] tabIndex 오류 해결

- dutchiepay/src/app/(modals)/images/page.jsx
- dutchiepay/src/app/(routes)/commerce/[id]/page.jsx
- dutchiepay/src/app/(routes)/mypage/myreview/page.jsx
- dutchiepay/src/app/_components/_commerce/Answer.jsx
- dutchiepay/src/app/_components/_commerce/Ask.jsx
- dutchiepay/src/app/_components/_commerce/Review.jsx
- dutchiepay/src/app/_components/_commerce/ReviewItem.jsx
- dutchiepay/src/app/_components/_mypage/MyReview.jsx
ex) fix/build-error-> main
build error 수정 및 마이페이지 내가 작성한 리뷰 목록 데이터 바인딩
> [fix] build error 수정 및 마이페이지 내가 작성한 리뷰 목록 데이터 바인딩

- dutchiepay/src/app/_components/_rating/RatingDistribution.jsx
ex) fix/NaN-error  -> main
0/0 일경우 NaN이 안뜨게 수정했습니다
> [fix] 제품 상세페이지 리뷰 0건 일때 에러 수정

- dutchiepay/src/app/_components/_mypage/MyReview.jsx
- dutchiepay/src/redux/store.js
ex) fix/redux-error -> dev
초기에 제가 수정했던 redux 에러 관련 코드 삭제했습니다
> [fix] 초기 redux 에러 코드 삭제

- dutchiepay/src/app/(routes)/commerce/[id]/page.jsx
- dutchiepay/src/app/(routes)/mypage/info/page.jsx
- dutchiepay/src/app/(routes)/mypage/like/page.jsx
- dutchiepay/src/app/(routes)/mypage/myorder/page.jsx
- dutchiepay/src/app/_components/_commerce/_product/ProductList.jsx
- dutchiepay/src/app/hooks/useClearUserData.jsx
- dutchiepay/src/app/hooks/useFetchDelivery.jsx
fix/infinite-roof -> main
reissue가 useEffect와 연관될 경우 모두 주석처리하여 무한루프 요청되지 않도록 수정
reissue 관련 부분 전부 수정해주세요
> [fix] reissue 중 무한루프 돌지 않도록 주석처리

- dutchiepay/src/app/(routes)/mypage/myreview/page.jsx
> [fix] 무한루프 오류 주석처리

- dutchiepay/src/app/(routes)/addition/page.jsx
- dutchiepay/src/app/(routes)/mypage/myreview/page.jsx
fix/addition -> main
상품 추가 시 주방/청소 카테고리를 주방청소로 변경
> [fix] 상품 추가 시 카테고리 값 변경

- dutchiepay/src/app/_components/_mypage/_order/OrderListDefault.jsx
fix/build-error -> main
build 오류 해결
> [fix] build import 오류 해결

- dutchiepay/src/app/(routes)/mypage/myorder/page.jsx
> [fix] console.log 추가

- dutchiepay/src/app/(routes)/mypage/myorder/page.jsx
> [fix] 초기 렌더링 제한 조건 제거

- dutchiepay/src/app/_components/Product.jsx
- dutchiepay/src/app/_components/_commerce/_product/ProductItemBottom.jsx
- dutchiepay/src/app/_components/_commerce/_product/ProductItemHeader.jsx
- dutchiepay/src/app/_components/_mypage/_order/OrderDetail.jsx
fix/product-mark -> main
1. 마감된 상품 grayscale 설정
2. 구매내역에서 판매/할인 가격에 수량 반영
3. 진행률 표기 오류 수정
4. 상품 목록 별점 값 바인딩
> [Fix] 상품 관련 오류 수정

- dutchiepay/src/app/_components/_commerce/_order/OrderSubmit.jsx
- dutchiepay/src/app/_components/_commerce/_order/PaymentChoice.jsx
- dutchiepay/src/app/hooks/usePayment.jsx
- dutchiepay/src/styles/commerce.css
fix/toss-pay -> main
1. 결제 수단에서 토스페이와 관련된 코드 제거
2. 결제하기 버튼 클릭 시 결제 수단을 선택하지 않았을 경우 alert가 뜨도록 설정
UI는 추후 수정 여유가 있을 때 작업하고자 합니다.
> [fix] 토스페이 제거 및 결제 수단 미선택 시 alert

- dutchiepay/src/app/_util/getFormatDate.js
ex) fix/getFormatDate-> main
getFormatDate 9시간 차이나는 에러 수정
convertToKST를 삭제하여 9시간 차이 안나게 수정했습니다
> [fix] getFormatDate 9시간 차이나는 에러 수정

- dutchiepay/src/app/(modals)/review/page.jsx
- dutchiepay/src/app/(routes)/commerce/[id]/page.jsx
- dutchiepay/src/app/(routes)/commerce/page.jsx
- dutchiepay/src/app/(routes)/mypage/info/page.jsx
- dutchiepay/src/app/(routes)/mypage/myask/page.jsx
- dutchiepay/src/app/(routes)/mypage/myorder/page.jsx
- dutchiepay/src/app/(routes)/mypage/myreview/page.jsx
- dutchiepay/src/app/_components/SectionSearch.jsx
- dutchiepay/src/app/_components/_commerce/_ask/AskForm.jsx
- dutchiepay/src/app/_components/_commerce/_order/DeliveryMessage.jsx
- dutchiepay/src/app/_components/_layout/Nav.jsx
- dutchiepay/src/app/_components/_mypage/MyReview.jsx
- dutchiepay/src/app/_components/_user/_login/LoginSubmit.jsx
- dutchiepay/src/app/_components/_user/_phone/PhoneAuth.jsx
- dutchiepay/src/app/hooks/useDeleteAsk.jsx
- dutchiepay/src/app/hooks/useDeleteReview.jsx
- dutchiepay/src/app/hooks/useFetchOrderProduct.jsx
- dutchiepay/src/app/hooks/useFetchReview.jsx
- dutchiepay/src/app/hooks/useLogout.jsx
> [fix] fetch 관련 reissue 주석처리

- dutchiepay/src/app/_components/_landing/ProductRank.jsx
fix/rank-link -> main
1. Hot 상품 랭킹 링크 추가
> [feat] Hot 상품 랭킹에서도 상품명 클릭 시 상세페이지로 이동하도록 링크 추가

- dutchiepay/src/app/(routes)/mypage/like/page.jsx
- dutchiepay/src/app/_components/_commerce/_productDetail/ProductStatus.jsx
fix/progress -> main
1. 상세페이지의 진행률 값 계산식 수정
2. 좋아요 상품 카테고리 전체 값이 ""로 표시되는 오류 수정
> [Fix] 진행률 수정 및 좋아요 상품 카테고리 오류 수정

- dutchiepay/src/app/_components/_commerce/_productDetail/ProductDetailTab.jsx
- dutchiepay/src/app/_components/_layout/Header.jsx
- dutchiepay/src/app/_components/_layout/HeaderHoverNav.jsx
fix/header-nav -> main
1. header 영역이 상품 상세페이지 header에 가려지지 않도록 header z-index를 높여주었습니다.
> [fix] header가 상품 상세페이지 header에 가려지는 오류 해결

- dutchiepay/src/app/(routes)/commerce/[id]/page.jsx
- dutchiepay/src/app/(routes)/mypage/info/page.jsx
- dutchiepay/src/app/(routes)/mypage/like/page.jsx
- dutchiepay/src/app/(routes)/mypage/myask/page.jsx
- dutchiepay/src/app/(routes)/mypage/myorder/page.jsx
- dutchiepay/src/app/_components/_commerce/_product/ProductList.jsx
- dutchiepay/src/app/hooks/useFetchDelivery.jsx
- dutchiepay/src/app/hooks/useFetchOrderProduct.jsx
- dutchiepay/src/app/hooks/useFetchReview.jsx
ex) fix/reissueTokenApi -> main
reissueTokenAPI useRef로 한번만 요청 보내게 수정했습니다
> [fix] reissueTokenAPI useRef로 한번만 요청 보내게 수정

- dutchiepay/src/app/_components/_commerce/_ask/AskItem.jsx
ex) fix/ask-answer-UI-> main
비밀글일때 답변 보이는 UI 수정, 답변 대기 상태일때 답변 UI 안보이게 수정했습니다
> [fix] 비밀글일때 답변 보이는 UI 수정, 답변 대기 상태일때 답변 UI 안보이게 수정

- dutchiepay/src/app/_components/_commerce/_product/ProductList.jsx
> [fix] reissue 코드 제거

- dutchiepay/src/app/_components/_commerce/_product/ProductList.jsx
ex) fix/reissueToken-product-list ->main
제품 리스트 reissue 에러 수정했습니다.
> [fix] 상품리스트 reissueToken error 수정

- dutchiepay/src/app/hooks/usePayment.jsx
fix/max-quantity -> main
결제 요청 시 주문 수량이 99개 이하일 경우 alert가 발생하는 오류 수정
> [fix] 최대 수량 조건 오류 수정

- dutchiepay/src/app/(modals)/ask/page.jsx
- dutchiepay/src/app/(routes)/mypage/myreview/page.jsx
- dutchiepay/src/app/_components/_commerce/OrderProductInfo.jsx
- dutchiepay/src/app/_components/_commerce/_ask/AskItem.jsx
- dutchiepay/src/app/_components/_commerce/_review/ReviewActions.jsx
- dutchiepay/src/app/_components/_commerce/_review/ReviewItem.jsx
- dutchiepay/src/app/_components/_mypage/MyReview.jsx
ex) fix/ask-review-bug -> main
후기,문의 UI 수정
제품 상세페이지 리뷰 rating API 이상하게 넘어와서 벡엔드에 수정 요청 드렸습니다
> [fix] 후기,문의 UI 수정

- dutchiepay/src/app/_components/_landing/HotCarousel.jsx
- dutchiepay/src/app/_components/_landing/HotProduct.jsx
- dutchiepay/src/app/_components/_landing/HotRanking.jsx
- dutchiepay/src/app/_components/_landing/MainArrow.jsx
- dutchiepay/src/app/_components/_landing/MainCarousel.jsx
- dutchiepay/src/app/_components/_landing/MainCarouselInfo.jsx
- dutchiepay/src/app/_components/_landing/MainProduct.jsx
- dutchiepay/src/app/_components/_landing/NewCarousel.jsx
- dutchiepay/src/app/_components/_landing/RecommendCarousel.jsx
- dutchiepay/src/app/_components/_layout/Floating.jsx
- dutchiepay/src/app/_components/_layout/Nav.jsx
refactor/dynamic -> main
Slider를 dynamic으로 import 하면서 ref 사용 시 warning이 발생해 dynamic import 제거하여 BEST practices 점수 복구
carousel에서 보이지 않을 경우 aria-hidden을 추가하여 접근성 강화
Hot Carousel 내에 불필요한 arrows가 일부 영역을 가리지 않도록 수정
상품 이미지에 sizes 속성을 추가하여 성능 강화
fill 속성을 사용하지 않는 일부 이미지에 width/height style을 적용하여 warning 제거
header 내 hover 컴포넌트를 dynamic import로 변경
해당 점수는 개발 모드에서 진행한 결과로 배포 시 조금 더 성능적으로는 높게 평가될 것으로 예상됩니다
> [refactor] slider 오류 해결, aria-hidden 속성으로 accessibility 보완, 추가 성능 보완

- dutchiepay/src/app/(routes)/order/page.jsx
- dutchiepay/src/app/_components/_commerce/_order/OrderInfo.jsx
- dutchiepay/src/app/_components/_commerce/_productDetail/OrderButton.jsx
- dutchiepay/src/app/_components/_commerce/_productDetail/ProductInfo.jsx
ex) fix/order-url -> main
order 정보 sessionStorage에 저장하게 수정했습니다
> [fix] /order URL query 제거

- dutchiepay/src/app/_components/_landing/RecommendCarousel.jsx
ex)  fix/updown-button-> main
floating MainProduct에 가려지는 에러 수정
> [fix] floatingButton 가려지는 에러 수정

- dutchiepay/src/app/_components/_commerce/_product/ProductList.jsx
fix/producct-list -> main
category 변경 시 상품 리스트가 호출되지 않는 오류 해결
> [fix] 공동구매 카테고리 변경 시 상품 리스트가 초기화되지 않는 오류 수정

- dutchiepay/src/app/(routes)/community/[id]/page.jsx
- dutchiepay/src/app/_components/_community/_free/HotPostList.jsx
- dutchiepay/src/app/_components/_community/_free/PostRecommend.jsx
- dutchiepay/src/app/_components/_community/_free/SimilarPostList.jsx
> [feat] 자유게시판 상세페이지 추천 게시글 구현

- dutchiepay/src/app/(routes)/community/[id]/page.jsx
- dutchiepay/src/app/(routes)/community/page.jsx
- dutchiepay/src/app/(routes)/community/write/[id]/page.jsx
- dutchiepay/src/app/(routes)/community/write/page.jsx
- dutchiepay/src/app/_components/_community/_common/PostDetailAction.jsx
- dutchiepay/src/app/hooks/useFetchUpdatePostData.jsx
feat/post-reissue -> main
자유게시판 게시글 관련 API에 reissue 코드를 추가
> [feat] 게시글 작성 API reissue 코드 추가

- dutchiepay/src/app/(routes)/used/detail/page.jsx
> [fix] 배포를 위한 나눔/거래 상세페이지 컴포넌트 일부 삭제

- dutchiepay/src/app/(routes)/mypage/mypost/page.jsx
- dutchiepay/src/app/_components/_mypage/MyPostList.jsx
ex)  fix/mypost-> main
내가 댓글 남긴 게시글 API 호출 안되는 에러 수정
> [fix] 내가 댓글 남긴 게시글 API 호출 안되는 에러 수정

- dutchiepay/src/app/_components/_community/_free/FreePostItem.jsx
ex) fix/free-community-> main
카테고리 데이터 한글로 수정, 프로필 이미지 데이터 바인딩 추가, description 영역 최소 크기 지정
> [fix] 자유게시판 UI 수정 및 카테고리 데이터 한글로 수정

- dutchiepay/src/app/hooks/useReissueToken.jsx
- dutchiepay/src/app/hooks/useRelogin.jsx
fix/refresh-remove -> main
API 명세서 수정으로 보안을 위해 refresh를 request body에 포함하지 않도록 수정하였습니다.
생략
> [fix] 자동로그인과 reissue request body에서 refresh 제거

- dutchiepay/src/app/(routes)/addition/page.jsx
fix/addition -> main
상품 추가 시 tag 값을 추가했습니다.
보기 편하도록 confirm에서는 띄어쓰기를 포함해서 출력하도록 해두었습니다. input 창 값을 그대로 가져갑니다.
> [fix] 상품 추가 시 tag 추가

- dutchiepay/src/app/(routes)/mypage/like/page.jsx
- dutchiepay/src/app/_components/Product.jsx
- dutchiepay/src/app/_components/_commerce/ProductLike.jsx
- dutchiepay/src/app/_components/_community/_common/PostContent.jsx
- dutchiepay/src/app/_components/_community/_free/FreePostForm.jsx
- dutchiepay/src/app/_components/_layout/Nav.jsx
- dutchiepay/src/app/_components/_search/CurrentSearch.jsx
- dutchiepay/src/app/_util/getImage.js
fix/test-error -> main
1. 이미지 업로드 시 이미지 이름에 파일 명을 제거하여 URL에 한국어가 포함되지 않도록 변경
2. 뒤로가기, 취소 등 일부 이동 링크에서 잘못된 URL 수정
3. HoverNav 영역을 보다 위로 이동시켜 끊김 없이 하위 depth 영역으로 이동할 수 있도록 변경
4. Product.jsx의 isLiked 초기값을 isLikePage에 따라 다르게 설정하도록 변경
모두 테스트 진행했고 문제 없음을 확인했습니다.
> [Fix] 커뮤니티 테스트 오류 사항 수정

- dutchiepay/src/app/_components/_community/_free/HotPostList.jsx
- dutchiepay/src/app/_components/_community/_free/PostRecommend.jsx
- dutchiepay/src/app/_components/_community/_free/SimilarPostList.jsx
ex)  fix/simialPost-> main
자유게시판 상세 우측 영역 유사한게시글, 핫한게시글 최소 영역 가지게 수정, 페이지 이동 영역 넓혔습니다.
닉네임과 프로필 이미지는 벡엔드 반환값 오류로 확인되어 요청드렸습니다. 프론트쪽은 문제없습니다
> [fix] 유사한 게시글 최소 영역 가지게 수정, 페이지 이동 영역 넓힘

- dutchiepay/src/app/(routes)/used/page.jsx
- dutchiepay/src/app/_components/_community/CommunityPostList.jsx
- dutchiepay/src/app/_components/_community/_used/TradePostItem.jsx
- dutchiepay/src/app/_components/_community/_used/TradePostList.jsx
- dutchiepay/src/app/_util/getNoPostMessage.js
ex) feat/trading-list-> main
거래나눔 게시판 리스트 조회 구현 및 검색 결과 없을시 멘트 수정
등록 시간과 나눔시 price가 0으로 넘어오는 오류는 벡엔드에 요청했습니다.
검색 결과 없을 때 멘트 커뮤니티에서 동일하게 사용되어 컴포넌트로 빼서 이번 pr에 마트/배달, 자유게시판에도 적용했습니다 .
> [feat,fix] 거래/나눔 게시판 리스트 조회 구현, 검색  결과 없을시 멘트 수정

- dutchiepay/src/app/_components/_community/_used/TradePostItem.jsx
ex) feat/trading-list-> main
나눔상품으로 표시되게 수정
> [fix] 상품 나눔시 나눔상품으로 표시되게 수정

- dutchiepay/src/app/_components/_community/_local/ChatButton.jsx
> [fix] import 오류 해결

- dutchiepay/src/app/_components/_user/AddInfoSubmit.jsx
> [fix] 소셜 회원 추가 정보 입력 시 trigger가 전달되지 않는 오류

- dutchiepay/src/app/_components/_commerce/_ask/AskForm.jsx
- dutchiepay/src/app/_components/_layout/Floating.jsx
- dutchiepay/src/app/_components/_mypage/MyReview.jsx
- dutchiepay/src/app/_components/_user/_login/LoginSubmit.jsx
- dutchiepay/src/app/hooks/useDeleteAsk.jsx
- dutchiepay/src/app/hooks/useDeleteReview.jsx
- dutchiepay/src/app/hooks/useLogout.jsx
- dutchiepay/src/app/hooks/useReviewDisplay.jsx
- dutchiepay/src/app/hooks/useSse.jsx
- dutchiepay/src/redux/slice/loginSlice.js
ex)fix/text-error-> main
테스트 에러 수정했습니다.
1 . 후기 수정 글자수 많아지면 더보기 이미지 안뜨는 에러수정
2. 알림창 클릭시 빨간점 안사라지는 에러 수정
3. 후기 이미지 더보기 아이콘 클릭시 더보기 안되는 에러 수정
4. 후기,리뷰 수정시 1000자 넘어가면  에러메시지 처리 완료
5. 알림 외부 영역 클릭 시 닫히게 수정
6. sse연결 조건 수정
7. 커스텀 훅 주석 처리된 부분 수정
> [fix] 테스트 에러 수정

- dutchiepay/src/app/hooks/useLogout.jsx
ex) fix/logout-error-> main
배포시 로그아웃에서 나는 에러 수정
> [fix] 불필요한 reissueResponse 삭제

- dutchiepay/src/app/hooks/useOauthLogin.jsx
소셜 로그인 시 전달된 유저 정보를 문자열에서 JSON 객체로 변경하여 안전하게 유저 정보를 저장할 수 있도록 변경
소셜 로그인이 배포 서버에서만 동작하여 테스트는 merge 후 진행하겠습니다.
> [fix] 소셜 로그인 시 response JSON 값으로 변경

- dutchiepay/src/app/_components/_mypage/_order/OrderActionButton.jsx
- dutchiepay/src/app/_components/_search/SearchContainer.jsx
- dutchiepay/src/app/hooks/useOrderStateAction.jsx
1. 리뷰 작성된 구매확정 상품이 리뷰 작성 팝업창이 뜨는 것은 사용자에게 혼선을 줄 수 있다고 판단되어 hasReviewed를 서버로부터 추가로 받아 구매확정이면서 hasReviewed가 true일 때는 후기 작성 버튼을 렌더링하지 않도록 조건을 추가해주었습니다.
2. OrderActionButton.jsx 파일 내 코드가 길어 버튼 클릭 함수를 custom hook으로 분리하여 가독성 있도록 리팩토링
정상적으로 동작 확인, 백엔드 API가 아직 배포되지 않아 후기 작성 테스트는 생략합니다.
> [fix] 리뷰 작성된 구매확정 상품을 hasReviewed를 통해 리뷰 작성 버튼 비활성화

- dutchiepay/src/app/hooks/useLogin.jsx
서버에서 refresh token(쿠키) 조회 시 쿠키 값이 반환되도록 쿠키의 설정 변경
배포 서버에서 테스트가 필요하여 생략합니다.
> [fix] 상위 도메인에서 쿠키 조회 가능하도록 쿠키 설정 변경

- dutchiepay/src/app/hooks/useLogin.jsx
- dutchiepay/src/app/hooks/useOauthLogin.jsx
이메일 자동 로그인 시 localStorage에 자동로그인 여부가 저장되지 않는 오류 수정
> [fix] 자동로그인 API가 호출되지 않는 오류 수정
